<a href="https://colab.research.google.com/github/TBKHori/Data-Analysis-Refresher-notes/blob/main/EDA_Lnz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introspection

In [ ]:
b = [1, 2, 3]


In [ ]:
b?

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [ ]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [ ]:
def add_numbers(a, b):
    """
    Add two numbers together

    Returns
    -------
    the_sum : type of arguments
    """
    return a + b

In [ ]:
add_numbers?

Signature: add_numbers(a, b)
Docstring:
Add two numbers together

Returns
-------
the_sum : type of arguments
File:      c:\users\lenovo\appdata\local\temp\ipykernel_22472\1411870314.py
Type:      function


In [ ]:
add_numbers?

Signature: add_numbers(a, b)
Docstring:
Add two numbers together

Returns
-------
the_sum : type of arguments
File:      c:\users\lenovo\appdata\local\temp\ipykernel_22472\1411870314.py
Type:      function


In [ ]:
np.*load*?

In [ ]:
def f(x, y, z):
    return (x + y) / z

a = 5
b = 6
c = 7.5


In [ ]:
%run ipython_script_test.py

Exception: File `'ipython_script_test.py'` not found.

In [ ]:
c

7.5

In [ ]:
result = f(a, b, c)

In [ ]:
result

1.4666666666666666

In [ ]:
 def f(x, y, z):
        return (x + y) / z

    a = 5
    b = 6
    c = 7.5

    result = f(a, b, c)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 4)

In [ ]:
x = 5
y = 7
if x > 5:
    x += 1

    y = 8

In [ ]:
%paste

UsageError: Line magic function `%paste` not found.


In [ ]:
%cpaste

UsageError: Line magic function `%cpaste` not found.


In [ ]:
 a = np.random.randn(100, 100)

In [ ]:
%timeit np.dot(a, a)
10000 loops, best of 3: 20.9 µs per loop

SyntaxError: invalid syntax (Temp/ipykernel_21328/1568678299.py, line 2)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
%debug?

Docstring:
::

  %debug [--breakpoint FILE:LINE] [statement ...]

Activate the interactive debugger.

This magic command support two ways of activating debugger.
One is to activate debugger before executing code.  This way, you
can set a break point, to step through the code from the point.
You can use this mode by giving statements to execute and optionally
a breakpoint.

The other one is to activate debugger in post-mortem mode.  You can
activate this mode simply running %debug without any argument.
If an exception has just occurred, this lets you inspect its stack
frames interactively.  Note that this will always work only on the last
traceback that occurred, so you must call this quickly after an
exception that you wish to inspect has fired, because if another one
occurs, it clobbers the previous one.

If you want IPython to automatically do this on every exception, see
the %pdb magic for more details.

.. versionchanged:: 7.3
    When running code, user variables are no longer exp

In [ ]:
for x in array:
    if x < pivot:
        less.append(x)
    else:
        greater.append(x)
a = 5; b = 6; c = 7

NameError: name 'array' is not defined

In [ ]:
results = []

In [ ]:
result = f(x, y, z)
g()
obj.some_method(x, y, z)
result = f(a, b, c, d=5, e='foo')

NameError: name 'f' is not defined

In [ ]:
a = [1, 2, 3]

In [ ]:
b = a

In [ ]:
a.append(4)
b

[1, 2, 3, 4]

In [ ]:
 data = [1, 2, 3]

In [ ]:
append_element(data, 4)


NameError: name 'append_element' is not defined

In [ ]:
a = 5
type(a)
a = 'foo'
type(a)

str

In [ ]:
5' + 5

SyntaxError: EOL while scanning string literal (Temp/ipykernel_21328/757742399.py, line 1)

In [ ]:
a = 4.5
b = 2
# String formatting, to be visited later
print('a is {0}, b is {1}'.format(type(a), type(b)))
a / b

a is <class 'float'>, b is <class 'int'>


2.25

In [ ]:
a = 5
isinstance(a, int)

True

In [ ]:
a = 5; b = 4.5
isinstance(a, (int, float))
isinstance(b, (int, float))

True

In [ ]:
a = 'foo'


In [ ]:
getattr(a, 'split')

<function str.split(sep=None, maxsplit=-1)>

In [ ]:
def isiterable(obj):
    try:
        iter(obj)
        return True
    except TypeError: # not iterable
        return False

In [ ]:
isiterable('a string')
isiterable([1, 2, 3])
isiterable(5)

False

In [ ]:
5 - 7
12 + 21.5
5 <= 2

False

In [ ]:
a = [1, 2, 3]
b = a
c = list(a)
a is b
a is not c

True

In [ ]:
a == c

True

In [ ]:
a = None
a is None

True

In [ ]:
a_list = ['foo', 2, [4, 5]]
a_list[2] = (3, 4)
a_list

['foo', 2, (3, 4)]

In [ ]:
a_tuple = (3, 5, (4, 5))
a_tuple[1] = 'four'

TypeError: 'tuple' object does not support item assignment

In [ ]:
ival = 17239871
ival ** 6

26254519291092456596965462913230729701102721

In [ ]:
fval = 7.243
fval2 = 6.78e-5

In [ ]:
3 / 2

1.5

In [ ]:
3 // 2

1

Strings


a = 'one way of writing a string' b = "another way"

In [ ]:
c = """
This is a longer string that
spans multiple lines
"""

In [ ]:
c.count('\n')

3

In [ ]:
a = 'this is a string'
a[10] = 'f'
b = a.replace('string', 'longer string')
b

TypeError: 'str' object does not support item assignment

In [ ]:
a

'this is a string'

In [ ]:
a = 5.6
s = str(a)
print(s)

5.6


In [ ]:
s = 'python'
list(s)
s[:3]

'pyt'

In [ ]:
s = '12\\34'
print(s)

12\34


In [ ]:
s = r'this\has\no\special\characters'
s

'this\\has\\no\\special\\characters'

In [ ]:
a = 'this is the first half '
b = 'and this is the second half'
a + b

'this is the first half and this is the second half'

In [ ]:
template = '{0:.2f} {1:s} are worth US${2:d}'

In [ ]:
template.format(4.5560, 'Argentine Pesos', 1)

'4.56 Argentine Pesos are worth US$1'

Bytes and Unicode

In [ ]:
val = "español"
val

'español'

In [ ]:
val_utf8 = val.encode('utf-8')
val_utf8
type(val_utf8)

bytes

In [ ]:
val_utf8.decode('utf-8')

'español'

In [ ]:
val.encode('latin1')
val.encode('utf-16')
val.encode('utf-16le')

b'e\x00s\x00p\x00a\x00\xf1\x00o\x00l\x00'

In [ ]:
bytes_val = b'this is bytes'
bytes_val
decoded = bytes_val.decode('utf8')
decoded  # this is str (Unicode) now

'this is bytes'

Dates and times

In [ ]:
from datetime import datetime, date, time
dt = datetime(2022, 5, 24, 22, 57, 21)
dt.day
dt.minute

57

In [ ]:
dt.date()
dt.time()

datetime.time(22, 57, 21)

In [ ]:
dt.strftime('%m/%d/%Y %H:%M')

'05/24/2022 22:57'

In [ ]:
datetime.strptime('20091031', '%Y%m%d')

datetime.datetime(2009, 10, 31, 0, 0)

In [ ]:
dt.replace(minute=0, second=0)

datetime.datetime(2022, 5, 24, 22, 0)

In [ ]:
dt2 = datetime(2011, 11, 15, 22, 30)
delta = dt2 - dt
delta
type(delta)

datetime.timedelta

In [ ]:
dt
dt + delta

datetime.datetime(2011, 11, 15, 22, 30)

Control Flow

if, elif, and else

if x < 0: print('It's negative')

if x < 0: print('It's negative') elif x == 0: print('Equal to zero') elif 0 < x < 5: print('Positive but smaller than 5') else: print('Positive and larger than or equal to 5')

In [ ]:
a = 5; b = 7
c = 8; d = 4
if a < b or c > d:
    print('Made it')

Made it


In [ ]:
4 > 3 > 2 > 1

True

for loops

for value in collection:

# do something with value
sequence = [1, 2, None, 4, None, 5] total = 0 for value in sequence: if value is None: continue total += value

sequence = [1, 2, 0, 4, 6, 5, 2, 1] total_until_5 = 0 for value in sequence: if value == 5: break total_until_5 += value

for i in range(4):
    for j in range(4):
        if j > i:
            break
        print((i, j))

In [ ]:
for i in range(4):
    for j in range(4):
        if j > i:
            break
        print((i, j))

(0, 0)
(1, 0)
(1, 1)
(2, 0)
(2, 1)
(2, 2)
(3, 0)
(3, 1)
(3, 2)
(3, 3)


for a, b, c in iterator:

# do something

while loops

x = 256 total = 0 while x > 0: if total > 500: break total += x x = x // 2

pass

if x < 0: print('negative!') elif x == 0:

# TODO: do somthing blah blah
pass
else: print('positive!')

range

In [ ]:
range(10)
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(0, 20, 2))
list(range(5, 0, -1))

[5, 4, 3, 2, 1]

In [ ]:
seq = [1, 2, 3, 4] 
for i in range(len(seq)): val = seq[i]

In [ ]:
sum = 0 
for i in range(100000):

IndentationError: expected an indented block (Temp/ipykernel_25588/312175510.py, line 2)

In [ ]:
# % is the modulo operator
if i % 3 == 0 or i % 5 == 0:
    sum += i

TypeError: unsupported operand type(s) for +=: 'builtin_function_or_method' and 'int'

Ternary expressions

In [ ]:
value = 
if

SyntaxError: invalid syntax (Temp/ipykernel_25588/330428849.py, line 1)

In [ ]:
x = 5
'Non-negative' if x >= 0 else 'Negative'

'Non-negative'

Built-in Data Structures, Functions,

Data Structures and Sequences

Tuple

In [ ]:
tup = 4, 5, 6
tup

(4, 5, 6)

In [ ]:
nested_tup = (4, 5, 6), (7, 8)
nested_tup

((4, 5, 6), (7, 8))

In [ ]:
tuple([4, 0, 2])
tup = tuple('string')
tup

('s', 't', 'r', 'i', 'n', 'g')

In [ ]:
tup[0]

's'

In [ ]:
tup = tuple(['foo', [1, 2], True])
tup[2] = False

TypeError: 'tuple' object does not support item assignment

In [ ]:
tup[1].append(3)
tup

('foo', [1, 2, 3], True)

In [ ]:
(4, None, 'foo') + (6, 0) + ('bar',)

(4, None, 'foo', 6, 0, 'bar')

In [ ]:
('foo', 'bar') * 4

('foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'bar')

Unpacking tuples

In [ ]:
tup = (4, 5, 6)
a, b, c = tup
b

5

In [ ]:
tup = 4, 5, (6, 7)
a, b, (c, d) = tup
d

7

In [ ]:
tmp = a a = b b = tmp

SyntaxError: invalid syntax (Temp/ipykernel_25588/2833571655.py, line 1)

In [ ]:
a, b = 1, 2
a
b
b, a = a, b
a
b

1

In [ ]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
for a, b, c in seq:
    print('a={0}, b={1}, c={2}'.format(a, b, c))

a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


In [ ]:
values = 1, 2, 3, 4, 5
a, b, *rest = values
a, b
rest

[3, 4, 5]

In [ ]:
a, b, *_ = values

Tuple methods

In [ ]:
a = (1, 2, 2, 2, 3, 4, 2)
a.count(2)

4

List

In [ ]:
a_list = [2, 3, 7, None]
tup = ('foo', 'bar', 'baz')
b_list = list(tup)
b_list
b_list[1] = 'peekaboo'
b_list

['foo', 'peekaboo', 'baz']

In [ ]:
gen = range(10)
gen
list(gen)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Adding and removing elements

In [ ]:
b_list.append('dwarf')
b_list

['foo', 'peekaboo', 'baz', 'dwarf']

In [ ]:
b_list.insert(1, 'red')
b_list

['foo', 'red', 'peekaboo', 'baz', 'dwarf']

In [ ]:
b_list.pop(2)
b_list

['foo', 'red', 'baz', 'dwarf']

In [ ]:
b_list.append('foo')
b_list
b_list.remove('foo')
b_list

['red', 'baz', 'dwarf', 'foo']

In [ ]:
'dwarf' in b_list

True

In [ ]:
'dwarf' not in b_list

False

Concatenating and combining lists

In [ ]:
[4, None, 'foo'] + [7, 8, (2, 3)]

[4, None, 'foo', 7, 8, (2, 3)]

In [ ]:
x = [4, None, 'foo']
x.extend([7, 8, (2, 3)])
x

[4, None, 'foo', 7, 8, (2, 3)]

everything = [] for chunk in list_of_lists: everything.extend(chunk)

everything = [] for chunk in list_of_lists: everything = everything + chunk

Sorting

In [ ]:
a = [7, 2, 5, 1, 3]
a.sort()
a

[1, 2, 3, 5, 7]

In [ ]:
b = ['saw', 'small', 'He', 'foxes', 'six']
b.sort(key=len)
b

['He', 'saw', 'six', 'small', 'foxes']

Binary search and maintaining a sorted list

In [ ]:
import bisect
c = [1, 2, 2, 2, 3, 4, 7]
bisect.bisect(c, 2)
bisect.bisect(c, 5)
bisect.insort(c, 6)
c

[1, 2, 2, 2, 3, 4, 6, 7]

Slicing

In [ ]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]
seq[1:5]

[2, 3, 7, 5]

In [ ]:
seq[3:4] = [6, 3]
seq

[7, 2, 3, 6, 3, 5, 6, 0, 1]

In [ ]:
seq[:5]
seq[3:]

[6, 3, 5, 6, 0, 1]

In [ ]:
seq[-4:]
seq[-6:-2]

[6, 3, 5, 6]

In [ ]:
seq[::2]

[7, 3, 3, 6, 1]

In [ ]:
seq[::2]

[7, 3, 3, 6, 1]

In [ ]:
seq[::-1]

[1, 0, 6, 5, 3, 6, 3, 2, 7]

Built-in Sequence Functions

enumerate

i = 0 for value in collection:

o something with value

In [ ]:
i += 1

for i, value in enumerate(collection):

do something with value

In [ ]:
some_list = ['foo', 'bar', 'baz']
mapping = {}
for i, v in enumerate(some_list):
    mapping[v] = i
mapping

{'foo': 0, 'bar': 1, 'baz': 2}

sorted

In [ ]:
sorted([7, 1, 2, 6, 0, 3, 2])
sorted('horse race')

[' ', 'a', 'c', 'e', 'e', 'h', 'o', 'r', 'r', 's']

In [ ]:
seq1 = ['foo', 'bar', 'baz']
seq2 = ['one', 'two', 'three']
zipped = zip(seq1, seq2)
list(zipped)

[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]

In [ ]:
seq3 = [False, True]
list(zip(seq1, seq2, seq3))

[('foo', 'one', False), ('bar', 'two', True)]

In [ ]:
for i, (a, b) in enumerate(zip(seq1, seq2)):
    print('{0}: {1}, {2}'.format(i, a, b))

0: foo, one
1: bar, two
2: baz, three


In [ ]:
pitchers = [('Nolan', 'Ryan'), ('Roger', 'Clemens'),
            ('Schilling', 'Curt')]
first_names, last_names = zip(*pitchers)
first_names
last_names

('Ryan', 'Clemens', 'Curt')

reversed

In [ ]:
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

dict

In [ ]:
empty_dict = {}
d1 = {'a' : 'some value', 'b' : [1, 2, 3, 4]}
d1

{'a': 'some value', 'b': [1, 2, 3, 4]}

In [ ]:
d1[7] = 'an integer'
d1
d1['b']

[1, 2, 3, 4]

In [ ]:
'b' in d1

True

In [ ]:
d1[5] = 'some value'
d1
d1['dummy'] = 'another value'
d1
del d1[5]
d1
ret = d1.pop('dummy')
ret
d1

In [ ]:
list(d1.keys())
list(d1.values())

['some value', [1, 2, 3, 4], 'an integer']

In [ ]:
d1.update({'b' : 'foo', 'c' : 12})
d1

{'a': 'some value', 'b': 'foo', 7: 'an integer', 'c': 12}

Creating dicts from sequences

In [ ]:
mapping = {} for key, value in zip(key_list, value_list): mapping[key] = value

mapping = dict(zip(range(5), reversed(range(5))))
mapping

SyntaxError: invalid syntax (Temp/ipykernel_25588/1897899492.py, line 1)

Default values
if key in some_dict: value = some_dict[key] else: value = default_value

value = some_dict.get(key, default_value)

In [ ]:
words = ['apple', 'bat', 'bar', 'atom', 'book']
by_letter = {}
for word in words:
    letter = word[0]
    if letter not in by_letter:
        by_letter[letter] = [word]
    else:
        by_letter[letter].append(word)
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

for word in words: letter = word[0] by_letter.setdefault(letter, []).append(word)

from collections import defaultdict by_letter = defaultdict(list) for word in words: by_letter[word[0]].append(word)

Valid dict key types

In [ ]:
hash('string')
hash((1, 2, (2, 3)))
hash((1, 2, [2, 3])) # fails because lists are mutable

TypeError: unhashable type: 'list'

In [ ]:
d[tuple([1, 2, 3])] = 5
d


TypeError: 'int' object does not support item assignment

set

In [ ]:
set([2, 2, 2, 1, 3, 3])
{2, 2, 2, 1, 3, 3}

{1, 2, 3}

In [ ]:
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}

In [ ]:
a.union(b)
a | b

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
a.intersection(b)
a & b

{3, 4, 5}

In [ ]:
c = a.copy()
c |= b
c
d = a.copy()
d &= b
d

{3, 4, 5}

In [ ]:
my_data = [1, 2, 3, 4]
my_set = {tuple(my_data)}
my_set

{(1, 2, 3, 4)}

In [ ]:
a_set = {1, 2, 3, 4, 5}
{1, 2, 3}.issubset(a_set)
a_set.issuperset({1, 2, 3})


True

In [ ]:
{1, 2, 3} == {3, 2, 1}

True

List, Set, and Dict Comprehensions

[

result = [] for val in collection: if

In [ ]:
strings = ['a', 'as', 'bat', 'car', 'dove', 'python']
[x.upper() for x in strings if len(x) > 2]

['BAT', 'CAR', 'DOVE', 'PYTHON']

dict_comp = {

set_comp = {

In [ ]:
unique_lengths = {len(x) for x in strings}
unique_lengths

{1, 2, 3, 4, 6}

In [ ]:
set(map(len, strings))

{1, 2, 3, 4, 6}

In [ ]:
loc_mapping = {val : index for index, val in enumerate(strings)}
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

Nested list comprehensions

In [ ]:
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'],
            ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]

names_of_interest = [] for names in all_data: enough_es = [name for name in names if name.count('e') >= 2] names_of_interest.extend(enough_es)

In [ ]:
result = [name for names in all_data for name in names
          if name.count('e') >= 2]
result

['Steven']

In [ ]:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
flattened = [x for tup in some_tuples for x in tup]
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

flattened = []

for tup in some_tuples: for x in tup: flattened.append(x)

In [ ]:
[[x for x in tup] for tup in some_tuples]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Functions

def my_function(x, y, z=1.5): if z > 1: return z * (x + y) else: return z / (x + y)

my_function(5, 6, z=0.7) my_function(3.14, 7, 3.5) my_function(10, 20)

Namespaces, Scope, and Local Functions
def func(): a = [] for i in range(5): a.append(i)

a = [] def func(): for i in range(5): a.append(i)

In [ ]:
a = None
def bind_a_variable():
    global a
    a = []
bind_a_variable()
print(a)

[]


Returning Multiple Values

def f(): a = 5 b = 6 c = 7 return a, b, c

a, b, c = f()

return_value = f()

def f(): a = 5 b = 6 c = 7 return {'a' : a, 'b' : b, 'c' : c}

Functions Are Objects

In [ ]:
states = ['   Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda',
          'south   carolina##', 'West virginia?']

In [ ]:
import re

def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?]', '', value)
        value = value.title()
        result.append(value)
    return result

In [ ]:
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [ ]:
def remove_punctuation(value):
    return re.sub('[!#?]', '', value)

clean_ops = [str.strip, remove_punctuation, str.title]

def clean_strings(strings, ops):
    result = []
    for value in strings:
        for function in ops:
            value = function(value)
        result.append(value)
    return result

In [ ]:
clean_strings(states, clean_ops)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [ ]:
for x in map(remove_punctuation, states):
    print(x)

   Alabama 
Georgia
Georgia
georgia
FlOrIda
south   carolina
West virginia


Anonymous (Lambda) Functions

def short_function(x): return x * 2

equiv_anon = lambda x: x * 2

def apply_to_list(some_list, f): return [f(x) for x in some_list]

ints = [4, 0, 1, 5, 6] apply_to_list(ints, lambda x: x * 2)

In [ ]:
strings = ['foo', 'card', 'bar', 'aaaa', 'abab']

In [ ]:
strings.sort(key=lambda x: len(set(list(x))))
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

Currying: Partial Argument Application
def add_numbers(x, y): return x + y

add_five = lambda y: add_numbers(5, y)

from functools import partial add_five = partial(add_numbers, 5)

Generators

In [ ]:
some_dict = {'a': 1, 'b': 2, 'c': 3}
for key in some_dict:
    print(key)

a
b
c


In [ ]:
dict_iterator = iter(some_dict)
dict_iterator

In [ ]:
list(dict_iterator)

['a', 'b', 'c']

In [ ]:
def squares(n=10):
    print('Generating squares from 1 to {0}'.format(n ** 2))
    for i in range(1, n + 1):
        yield i ** 2

In [ ]:
gen = squares()
gen

<generator object squares at 0x0000018EB9F92DD0>

In [ ]:
for x in gen:
    print(x, end=' ')

Generating squares from 1 to 100
1 4 9 16 25 36 49 64 81 100 

Generator expresssions

In [ ]:
gen = (x ** 2 for x in range(100))
gen

<generator object <genexpr> at 0x0000018EB9FC5270>

def _make_gen(): for x in range(100): yield x ** 2 gen = _make_gen()

In [ ]:
sum(x ** 2 for x in range(100))
dict((i, i **2) for i in range(5))

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

itertools module

In [ ]:
import itertools
first_letter = lambda x: x[0]
names = ['Alan', 'Adam', 'Wes', 'Will', 'Albert', 'Steven']
for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names)) # names is a generator

A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']


Errors and Exception Handling

In [ ]:
float('1.2345')
float('something')

In [ ]:
def attempt_float(x):
    try:
        return float(x)
    except:
        return x

In [ ]:
attempt_float('1.2345')
attempt_float('something')

'something'

In [ ]:
float((1, 2))

TypeError: float() argument must be a string or a number, not 'tuple'

In [ ]:
def attempt_float(x):
    try:
        return float(x)
    except ValueError:
        return x

In [ ]:
attempt_float((1, 2))

TypeError: float() argument must be a string or a number, not 'tuple'

In [ ]:
def attempt_float(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return x

f = open(path, 'w')

try: write_to_file(f) finally: f.close()

f = open(path, 'w')

try: write_to_file(f) except: print('Failed') else: print('Succeeded') finally: f.close()

Exceptions in IPython

In [10]: %run examples/ipython_bug.py

AssertionError Traceback (most recent call last) /home/wesm/code/pydata-book/examples/ipython_bug.py in () 13 throws_an_exception() 14 ---> 15 calling_things()

/home/wesm/code/pydata-book/examples/ipython_bug.py in calling_things() 11 def calling_things(): 12 works_fine() ---> 13 throws_an_exception() 14 15 calling_things()

/home/wesm/code/pydata-book/examples/ipython_bug.py in throws_an_exception() 7 a = 5 8 b = 6 ----> 9 assert(a + b == 10) 10 11 def calling_things():

AssertionError:

Files and the Operating System

In [ ]:
%pushd book-materials

[WinError 2] The system cannot find the file specified: 'book-materials'
c:\Users\LENOVO\Documents\Project{CODE}\Data Analysis\Portfolio Project\Notebooks


['c:\\Users\\LENOVO\\Documents\\Project{CODE}\\Data Analysis\\Portfolio Project\\Notebooks']

In [ ]:
path = 'examples/segismundo.txt'
f = open(path)

FileNotFoundError: [Errno 2] No such file or directory: 'examples/segismundo.txt'

for line in f: pass

In [ ]:
lines = [x.rstrip() for x in open(path)]
lines

FileNotFoundError: [Errno 2] No such file or directory: 'examples/segismundo.txt'

In [ ]:
f.close()

NameError: name 'f' is not defined

In [ ]:
with open(path) as f:
    lines = [x.rstrip() for x in f]

FileNotFoundError: [Errno 2] No such file or directory: 'examples/segismundo.txt'

In [ ]:
f = open(path)
f.read(10)
f2 = open(path, 'rb')  # Binary mode
f2.read(10)

FileNotFoundError: [Errno 2] No such file or directory: 'examples/segismundo.txt'

In [ ]:
f.tell()
f2.tell()

NameError: name 'f' is not defined

In [ ]:
import sys
sys.getdefaultencoding()

'utf-8'

In [ ]:
f.seek(3)
f.read(1)

NameError: name 'f' is not defined

In [ ]:
f.close()
f2.close()

NameError: name 'f' is not defined

In [ ]:
with open('tmp.txt', 'w') as handle:
    handle.writelines(x for x in open(path) if len(x) > 1)
with open('tmp.txt') as f:
    lines = f.readlines()
lines

FileNotFoundError: [Errno 2] No such file or directory: 'examples/segismundo.txt'

In [ ]:
import os
os.remove('tmp.txt')

In [ ]:
with open(path) as f:
    chars = f.read(10)
chars

FileNotFoundError: [Errno 2] No such file or directory: 'examples/segismundo.txt'

In [ ]:
with open(path, 'rb') as f:
    data = f.read(10)
data

FileNotFoundError: [Errno 2] No such file or directory: 'examples/segismundo.txt'

In [ ]:
data.decode('utf8')
data[:4].decode('utf8')

NameError: name 'data' is not defined

In [ ]:
sink_path = 'sink.txt'
with open(path) as source:
    with open(sink_path, 'xt', encoding='iso-8859-1') as sink:
        sink.write(source.read())
with open(sink_path, encoding='iso-8859-1') as f:
    print(f.read(10))

FileNotFoundError: [Errno 2] No such file or directory: 'examples/segismundo.txt'

In [ ]:
os.remove(sink_path)

NameError: name 'sink_path' is not defined

In [ ]:
f = open(path)
f.read(5)
f.seek(4)
f.read(1)
f.close()

NameError: name 'path' is not defined

NumPy Basics: Arrays and Vectorized Computation

In [ ]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [ ]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 32 ms
Wall time: 2.01 s


The NumPy ndarray: A Multidimensional Array Object

In [ ]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[ 0.0929,  0.2817,  0.769 ],
       [ 1.2464,  1.0072, -1.2962]])

In [ ]:
data * 10
data + data

array([[-0.4094,  0.9579, -1.0389],
       [-1.1115,  3.9316,  2.7868]])

In [ ]:
data.shape
data.dtype

dtype('float64')

Creating ndarrays

In [ ]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2.ndim
arr2.shape

(2, 4)

In [ ]:
arr1.dtype
arr2.dtype

dtype('int32')

In [ ]:
np.zeros(10)
np.zeros((3, 6))
np.empty((2, 3, 2))

array([[[1.3979e-311, 3.1620e-322],
        [0.0000e+000, 0.0000e+000],
        [1.0186e-312, 8.6723e-067]],

       [[4.8138e-038, 7.4984e-067],
        [4.0419e-037, 4.4728e-033],
        [6.0337e+174, 3.6971e-033]]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Data Types for ndarrays

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

dtype('int32')

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [ ]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

Arithmetic with NumPy Arrays

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
1 / arr
arr ** 0.5

array([[1.    , 1.4142, 1.7321],
       [2.    , 2.2361, 2.4495]])

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Basic Indexing and Slicing

In [ ]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])